### ISSUE TITLE
How long will the HTTP connection be open?

### ISSUE THREAD

**Issue by renepickhardt** [conscott/get-lightning-paid#1]
https://github.com/conscott/get-lightning-paid/blob/d80535c6e21c73151680263cde08fd5a52632e88/app.py#L87

in my donation plugin I am polling for the complete payment status all three seconds. I was about to use the waitinvlice API call but I was not sure if the tcp socket / http connection would stay open so long. I heard that with reverse proxies configures everywhere on the internet for longpolling one should never assume that and http request can live longer thatn 30 to 60 seconds. 

Another solution of course would be to use web sockets.

**Comment by conscott** [comment]
Yeah, in general I think it's a bad idea to try to use `waitinvoice`, even though I used it on my own website (I intend to change it to polling). By default most web servers will timeout on an http request in 60 seconds. In my case, I had to manually configure both uwsgi and nginx to 600 second timeouts, which match the 600 second default invoice expiry. This is bad form, in that you can't really expect anything downstream to wait that long, and HTTP isn't really designed for long lived requests. It may be okay if you had really short expiry, but I can't really think of an application that would specifically want that. 

Agree event notifications / web sockets would be preferred, but polling with `listinvoices` is probably fine for now.

**Comment by renepickhardt** [comment]
or adding an event based message queue  but that is a lot of overhead for the middleware

**Comment by conscott** [comment]
FYI - changed to polling on my site 
https://github.com/conscott/conscott.github.io/commit/37d9fc8b4f3371f116b7c1f85c3a9f0cc2993630

**Comment by renepickhardt** [comment]
nice (:
